/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "var(--font-sans)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        mono: [
          "var(--font-mono)",
          "ui-monospace",
          "SFMono-Regular",
          "monospace",
        ],
        "nano-caps": ["var(--font-sans)"],
        display: ["var(--font-sans)"],
        micro: ["var(--font-sans)"],
        "section-heading": ["var(--font-sans)"],
        "mono-id": ["var(--font-mono)"],
        "body-sm-bold": ["var(--font-sans)"],
        "page-title": ["var(--font-sans)"],
        "label-badge": ["var(--font-sans)"],
        "body-sm": ["var(--font-sans)"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        // Premium Design System Colors
        "priority-high-bg": "#ffedd5",
        "priority-high-text": "#c2410c",
        "priority-medium-bg": "#fef9c3",
        "priority-medium-text": "#a16207",
        "status-resolved-bg": "#dcfce7",
        "status-resolved-text": "#15803d",
        "status-progress-bg": "#dbeafe",
        "status-progress-text": "#1d4ed8",
        "status-open-bg": "#fee2e2",
        "status-open-text": "#b91c1c",
        "status-closed-bg": "#f1f5f9",
        "status-closed-text": "#64748b",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "primary-fixed": "#aaf854",
        "primary-fixed-dim": "#8fdb39",
        "on-primary-fixed": "#0f2000",
        "on-primary-fixed-variant": "#2d5000",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#ffd7f2",
        "tertiary-fixed-dim": "#ffacec",
        "on-tertiary-fixed": "#390034",
        "on-tertiary-fixed-variant": "#7b1c71",
        "chart-1": "#93c5fd",
        "chart-2": "#3b82f6",
        "chart-3": "#1d4ed8",
        "chart-4": "#1e3a8a",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        "element-gap": "8px",
        "card-padding": "20px",
        "page-margin": "24px",
        "toolbar-y": "16px",
        "section-gap": "12px",
        base: "4px",
        "icon-gap": "6px",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
