// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const CHANNEL_BINDING_PARAM = /([?&])channel_binding=require(&?)/i;

function stripTrailingSeparators(value: string): string {
  return value.replace(/[?&]$/, "");
}

function normalizeDatabaseUrl(input?: string | null): string {
  const url = input?.trim();
  if (!url) {
    throw new Error("DATABASE_URL is not set. Check your .env file.");
  }

  let normalized = url.replace(CHANNEL_BINDING_PARAM, "$1");
  normalized = stripTrailingSeparators(normalized);
  return normalized;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: normalizeDatabaseUrl(process.env["DATABASE_URL"]),
  },
});
